name: TOSN Discord Notifier

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

permissions:
  contents: write

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 가져오기
        uses: actions/checkout@v4

      - name: Python 설치
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: 필요한 프로그램 설치
        run: pip install -r requirements.txt

      - name: 봇 실행
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python bot.py
